FROM critoma/amd64_u24_noble_ism_security

ENV SHELL=/bin/bash

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y default-jre-headless \
    maven \
    build-essential \
    mpich \
    openssh-server \
    cmake \
    libopenmpi-dev \
    openmpi-bin \
    openssh-client \
    libssl-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN mkdir -p /var/run/sshd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    echo "    UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config

RUN mkdir -p /root/.ssh && \
    touch /root/.ssh/authorized_keys && \
    chmod 700 /root/.ssh && \
    ssh-keygen -t rsa -b 4096 -f /root/.ssh/id_rsa -N ""

ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

WORKDIR /app
COPY c03-04-openmpi-openmp-c/main.cpp .
COPY c03-04-openmpi-openmp-c/CMakeLists.txt .

RUN cmake . && make
RUN cat > start.sh <<EOF
#!/bin/bash
service ssh start

cp /root/.ssh/id_rsa.pub /shared_keys/
echo "c03: Public key copied to shared volume"
echo "c03: waiting for c04 to be ready..."
sleep 10
if ssh -o ConnectTimeout=10 -o BatchMode=yes root@c04 "echo 'SSH connection successful'" 2>/dev/null; then
    echo "c03: SSH connection to c04 successful"
else
    echo "c03: SSH connection to c04 failed, but continuing..."
fi

mvn exec:java -Dexec.mainClass=MainKt
EOF
RUN chmod +x start.sh

COPY ./c03-clsub-openmpi/pom.xml .
RUN mvn dependency:go-offline

COPY ./c03-clsub-openmpi/src src/
RUN mvn package

# run app
CMD ["./start.sh"]